### ISSUE TITLE
[DOCS] Improve docs structure

### ISSUE THREAD

**Issue by nialexsan** [onflow/docs#183]
### Issue to be solved

Docs are not very readable and dev friendly. it's difficult to navigate the website without using search, the sections are not clearly defined

### Suggest A Solution

change docs structure according to the doc
https://www.notion.so/dapperlabs/Dev-Documentation-breakdown-28be7d292dee4049a3db43e457a57151

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/docs/issues/180
- [ ] https://github.com/onflow/docs/issues/186
- [ ] [DOCS] About Flow
- [ ] [DOCS] Using Flow
- [ ] https://github.com/onflow/docs/issues/187
- [ ] https://github.com/onflow/docs/issues/188
- [ ] [DOCS] Core Contracts
```
