### ISSUE TITLE
Audit and Update Docs for Cadence 1.0

### ISSUE THREAD

**Issue by gregsantos** [onflow/docs#531]
refer to https://forum.flow.com/t/update-on-cadence-1-0/5197 for changes

```[tasklist]
### Tasks
- [x] replace pub and priv with access(all) and access(self)
- [ ] https://github.com/onflow/docs/issues/553
- [ ] https://github.com/onflow/docs/issues/554
- [ ] https://github.com/onflow/docs/issues/559
- [ ] https://github.com/onflow/docs/issues/560
- [ ] https://github.com/onflow/docs/issues/561
- [ ] https://github.com/onflow/docs/issues/562
- [ ] https://github.com/onflow/docs/issues/563
- [ ] https://github.com/onflow/docs/issues/564
- [ ] https://github.com/onflow/docs/issues/565
- [ ] https://github.com/onflow/docs/issues/566
- [ ] https://github.com/onflow/docs/issues/567
```

```[tasklist]
### Pages needing Updates
```

**Comment by joshuahannan** [comment]
Marking this as in Review since it seems like we've mostly completed all of these

**Comment by gregsantos** [comment]
Thanks @joshuahannan !
