### ISSUE TITLE
[EPIC] FlowEVM Docs - Cadence Dev

### ISSUE THREAD

**Issue by gregsantos** [onflow/docs#575]
**Path**: Build/Integrating with EVM

#### Reference
- [Cadence EVM Snippets gitbook](https://fw-internal-doc.gitbook.io/evm#write-evm-contract-by-coa)
- [EVM Support FLIP](https://github.com/onflow/flips/blob/d01024385bf72e8d566f2502c343780603624210/protocol/20231116-evm-support.md)

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/docs/issues/682
- [ ] https://github.com/onflow/docs/issues/683
- [ ] https://github.com/onflow/docs/issues/686
- [ ] https://github.com/onflow/docs/issues/684
- [x] How to deploy contract using a COA
- [x] Running EVM transactions from Cadence
- [x] Moving Assets Using the EVM Bridge Contract
- [ ] https://github.com/onflow/docs/issues/864
- [ ] https://github.com/onflow/docs/issues/687
```
