### ISSUE TITLE
[MILESTONE] Start of Cadence 1.0 Testnet Migration Phase

### ISSUE THREAD

**Issue by gregsantos** [onflow/docs#625]
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/docs/issues/624
- [ ] https://github.com/onflow/docs/issues/529
- [ ] https://github.com/onflow/docs/issues/623
- [ ] https://github.com/onflow/flow-cli/issues/1433
```
