### ISSUE TITLE
Update EVM Content

### ISSUE THREAD

**Issue by Aliserag** [onflow/docs#656]
```[tasklist]
### Tasks
- [x] Why EVM on Flow: https://docs.google.com/document/d/1agIC-CmnPUuEn_rE6Wmqh5Ba_OGS8EWJRJcpCklespA/edit?usp=sharing
- [x] Using EVM: https://docs.google.com/document/d/1yp0bymw672orSqHwVFLS7bOSfTShRu234JQovxUKtnY/edit?usp=sharing
- [x] Fees: https://docs.google.com/document/d/12gqByT8UmDi9gSI_d-9jpmfk1jCvXLJf7_eWjXufDRo/edit?usp=sharing
- [x] Accounts: https://docs.google.com/document/d/1zcOPDq2N24l78YBSus379KPdKGEmuoepj0Xr49pexV8/edit?usp=sharing
- [x] Hardhat: https://docs.google.com/document/d/1EOUUV-F3oa0ofOpOLJ_iz3xCnPwQV4wUgPBlrUVm-KE/edit?usp=sharing
- [x] Remix: https://docs.google.com/document/d/1QHGBLgLtQqrzIdSzVbKVUsIZBHhUmhBGlZOe8ngos5k/edit?usp=sharing
- [x] Web3.js: https://docs.google.com/document/d/17RJnqCMC8qfb0OPXFboSwtljSDl-lxkNL1SDvuz-ULM/edit?usp=sharing
- [x] Cross-VM Bridge: https://docs.google.com/document/d/12XyBef5j7LC3beyu6fkS2uSZLHs14jEf0xiDwckAxyo/edit?usp=sharing
```

**Comment by chasefleming** [comment]
@Aliserag task 1 already looks complete. Can you confirm?

**Comment by chasefleming** [comment]
Looks like these have all been completed. Marking as done.
