### ISSUE TITLE
New Landing page polish

### ISSUE THREAD

**Issue by bthaile** [onflow/docs#701]
## Task List

1. [x] **Hero links and text:**
   - [x] Update the link for "Learn Cadence Beginner-1" to: https://academy.ecdao.org/en/catalog/courses/learn-cadence-beginner-1.
   - [x] Change "Flow Quest" link to: https://flownaut.ecdao.org/en, as Flow Quest isn't maintained anymore. Update name to Flownaut.
   - [x] Change "Beginner DApp" to "Hello World" and link to: https://developers.flow.com/build/getting-started/quickstarts/hello-world

2. [x] **UI/UX Adjustments:**
   - [x] For 'Read Docs' button, add change on-hover, remove the underline for hyperlinks and instead add an opacity reduction to match other button behaviors.

3. [x] **Content Improvements:**
   - [x] Replace 'Latest notes' on buttons with short descriptions for clarity under the hero section (i.e., office hours)

4. [x] **Documentation and Guides:**
   - [x] Direct "Read Docs" to https://developers.flow.com/build/flow.
   - [x] Update links for:
     - "Create Fungible Tokens": https://developers.flow.com/build/guides/fungible-token
     - "Launch an NFT": https://developers.flow.com/build/guides/nft
     - "Quickstarts": https://academy.ecdao.org/en/quickstarts
   - [x] Add resources for:
     - "Emerald Snippets": https://academy.ecdao.org/en/snippets
     - "Emerald Examples": https://academy.ecdao.org/en/cadence-by-example
     - "Cookbook": https://cookbook.flow.com/

5. [x] **Ecosystem & Tools:**
   - [x] Rename "Ecosystem & Tools" to "Ecosystem" and link to https://developers.flow.com/ecosystem.
   - [x] Add links for:
     - "Cadence": https://cadence-lang.org/
     - "Playground": https://play.flow.com/

6. [x] **Key Features:**
   - [x] Include the following development basics links:
     - "Why Flow": https://developers.flow.com/build/flow
     - "Smart Accounts": https://developers.flow.com/build/basics/accounts
     - "Bundle and Scripted Transactions": https://developers.flow.com/build/basics/transactions
     - "Scripted Queries": https://developers.flow.com/build/basics/scripts
     - "EVM Equivalency" (with updated description to "Coming in from EVM? Learn how to launch your app fast"): https://developers.flow.com/evm/about

7. [x] **Visual Content Updates:**
   - [x] For "Start building", update pictures to screenshots of "Emerald Examples" and the "Cookbook". Could ask Fernando to make assets but don't think it's worth waiting for.
   - [x] Apply the same img asset update for "Quickstarts" under guides.

8. [x] **Social Media Links:**
   - [x] Update Twitter link to: https://twitter.com/flow_blockchain

9. [x] **Enhancement Suggestion:**
   - [x] Consider adding on-scroll transitions with Framer Motion for a dynamic UI experience. Suggest trying to get GPT to update it with onscroll transition animations, if it doesn't work nicely right away I wouldn't waste more time.
