### ISSUE TITLE
[EPIC] Spilt Dev Docs into Cadence 1.0 and Legacy

### ISSUE THREAD

**Issue by gregsantos** [onflow/docs#738]
```[tasklist]
### Tasks
- [x] Redeploy Legacy Docs to new domain
- [x] Add Info Banner callouts to available Legacy docs
- [ ] https://github.com/onflow/docs/issues/531
```

- [ ] https://developers.flow.com/tools/clients/flow-go-sdk
- [ ] https://developers.flow.com/tools/clients/fcl-js
- [ ] https://developers.flow.com/tools/clients/fcl-js/api#on-chain-interactions
- [ ] https://developers.flow.com/tools/clients/fcl-js/sdk-guidelines
- [ ] https://developers.flow.com/tools/clients/fcl-js/configure-fcl
- [ ] https://developers.flow.com/tools/flow-dev-wallet
- [ ] https://developers.flow.com/build/basics/transactions
- [ ] https://developers.flow.com/build/basics/scripts
- [ ] https://developers.flow.com/build/basics/fees
- [ ] https://developers.flow.com/build/guides/flow-app-quickstart
- [ ] https://developers.flow.com/build/core-contracts/flow-nft/MetdataViews/MetadataViews (all Structs and Resources)
- [ ] https://developers.flow.com/build/core-contracts/flow-nft/NonFungibleToken
- [ ] https://developers.flow.com/build/core-contracts/nft-storefront
- [ ] https://developers.flow.com/build/core-contracts/staking-collection
- [ ] https://developers.flow.com/build/smart-contracts/best-practices/design-patterns
- [ ] https://developers.flow.com/build/smart-contracts/best-practices/anti-patterns
- [ ] https://developers.flow.com/build/guides/fungible-token
- [ ] https://developers.flow.com/build/guides/nft
- [ ] https://developers.flow.com/tools/nft-catalog
- [ ] https://developers.flow.com/build/guides/account-linking
- [ ] https://developers.flow.com/build/guides/account-linking/child-accounts

**Comment by nialexsan** [comment]
new vercel deployment:
https://docs-git-legacy-onflow.vercel.app/

needs https://github.com/dapperlabs/flow-devex-infrastructure/pull/151 for a domain name
